use libtyr::{self, Context, RenderBuilder};
use std::io::Cursor;

#[test]
fn render() {
    let context: Context = ::setup_context().expect("Unable to setup context!");
    let tables_metadata = libtyr::fetch(&context).expect("Unable to fetch metadata!");
    let mut output = Cursor::new(Vec::new());
    if let Ok(renderer) = RenderBuilder::default().file_per_table(false).build() {
        match renderer.render(&tables_metadata, &mut output) {
            Ok(_) => {
                let vec = output.into_inner();
                let out_str = String::from_utf8_lossy(&vec);
                assert!(out_str.starts_with("//! ORM generated by tyr"));
            }
            Err(e) => assert!(false, e),
        }
    } else {
        assert!(false, "RenderBuilder build failed!");
    }
}
